/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ApiExtensionScoreRouteImport } from './routes/api/extension-score'
import { Route as ApiTripChatRouteImport } from './routes/api/trip-chat'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionScoreRoute = ApiExtensionScoreRouteImport.update({
  id: '/api/extension-score',
  path: '/api/extension-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripChatRoute = ApiTripChatRouteImport.update({
  id: '/api/trip-chat',
  path: '/api/trip-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/plan': typeof PlanRoute
  '/api/extension-score': typeof ApiExtensionScoreRoute
  '/api/trip-chat': typeof ApiTripChatRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/plan': typeof PlanRoute
  '/api/extension-score': typeof ApiExtensionScoreRoute
  '/api/trip-chat': typeof ApiTripChatRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/plan': typeof PlanRoute
  '/api/extension-score': typeof ApiExtensionScoreRoute
  '/api/trip-chat': typeof ApiTripChatRoute
  '/api/weather': typeof ApiWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/plan'
    | '/api/extension-score'
    | '/api/trip-chat'
    | '/api/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/plan'
    | '/api/extension-score'
    | '/api/trip-chat'
    | '/api/weather'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/plan'
    | '/api/extension-score'
    | '/api/trip-chat'
    | '/api/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  PlanRoute: typeof PlanRoute
  ApiExtensionScoreRoute: typeof ApiExtensionScoreRoute
  ApiTripChatRoute: typeof ApiTripChatRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension-score': {
      id: '/api/extension-score'
      path: '/api/extension-score'
      fullPath: '/api/extension-score'
      preLoaderRoute: typeof ApiExtensionScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip-chat': {
      id: '/api/trip-chat'
      path: '/api/trip-chat'
      fullPath: '/api/trip-chat'
      preLoaderRoute: typeof ApiTripChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  PlanRoute: PlanRoute,
  ApiExtensionScoreRoute: ApiExtensionScoreRoute,
  ApiTripChatRoute: ApiTripChatRoute,
  ApiWeatherRoute: ApiWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
